import type { Metadata } from "next";
import { Provider } from "@/context/Provider";
import { quicksand } from "./ui/fonts";
import { poppins } from "./ui/fonts";
import { monteCarlo } from "./ui/fonts";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Cafe POS System",
  description: "Generated by nextjs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body> */}
      <body className={`${quicksand.variable} ${poppins.variable} ${monteCarlo.variable} antialiased dark text-foreground bg-background`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
